import { StyleSheet } from "react-native";

// ── Design tokens semánticos del dominio ─────────────────────────────────────
export const GREEN = "#2EAA6E";
export const GREEN_LIGHT = "#E6F7EF";
export const RED = "#E03E3E";
export const RED_LIGHT = "#FDEAEA";
export const GRAY_BG = "#F6F7FB";
export const GRAY_BORDER = "#E2E6EF";
export const GRAY_TEXT = "#7B8499";
export const GRAY_LIGHT = "#F0F2F7";
export const INK = "#111827";
export const INK_SOFT = "#374151";

export const T = StyleSheet.create({
  display: { fontSize: 30, fontWeight: "800", color: INK, letterSpacing: -0.5 },
  h1: { fontSize: 24, fontWeight: "700", color: INK, letterSpacing: -0.3 },
  h2: { fontSize: 20, fontWeight: "700", color: INK },
  h3: { fontSize: 18, fontWeight: "600", color: INK_SOFT },
  body: { fontSize: 17, fontWeight: "400", color: INK_SOFT },
  bodyBold: { fontSize: 17, fontWeight: "700", color: INK },
  bodyBoldC: { fontSize: 17, fontWeight: "700", color: INK, right: 20 },
  label: {
    fontSize: 15,
    fontWeight: "700",
    color: GRAY_TEXT,
    letterSpacing: 0.3,
  },
  caption: { fontSize: 16, fontWeight: "400", color: GRAY_TEXT },
  captionMd: { fontSize: 16, fontWeight: "600", color: GRAY_TEXT },
  number: { fontSize: 36, fontWeight: "900", color: INK, letterSpacing: -1 },
  mono: { fontSize: 22, fontWeight: "700" },
});

export const s = StyleSheet.create({
  stepRow: { flexDirection: "row", minHeight: 0 },
  timelineCol: { width: 20, alignItems: "center" },
  contentCol: { flex: 1, paddingLeft: 14, paddingBottom: 20 },
  circle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
  },
  circleActive: { backgroundColor: "#0077EE" },
  circleInactive: { backgroundColor: "#D1D5DB" },
  circleText: { color: "#fff", fontWeight: "700", fontSize: 16 },
  line: {
    width: 2,
    flex: 1,
    backgroundColor: GRAY_BORDER,
    marginVertical: 2,
    zIndex: 1,
  },
  stepHeader: {
    flexDirection: "row",
    alignItems: "center",
    height: 32,
    gap: 8,
  },
  activeBlock: { marginTop: 10 },
  inputDropdownWrapper: {
    position: "relative",
    zIndex: 100,
    marginBottom: 0,
  },
  dropdownFloat: {
    position: "absolute",
    top: 56,
    left: 0,
    right: 0,
    backgroundColor: "#F0F2F7",
    borderRadius: 16,
    borderWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 4,
    zIndex: 20,
    padding: 8,
  },
  btnRemove: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: RED_LIGHT,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#FECACA",
  },
  modoBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    marginBottom: 10,
  },
  productoModal: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: GRAY_BORDER,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  modalHeader: { flexDirection: "row", alignItems: "center", marginBottom: 14 },
  closeBtnRed: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: RED,
    alignItems: "center",
    justifyContent: "center",
  },
  modalGrid: { flexDirection: "row", gap: 12, marginBottom: 12 },
  modalField: { flex: 1 },
  cantidadInput: {
    backgroundColor: GRAY_LIGHT,
    borderWidth: 1,
    borderColor: GRAY_BORDER,
    borderRadius: 10,
    padding: 12,
    fontSize: 26,
    fontWeight: "700",
    color: INK,
    textAlign: "center",
    marginTop: 6,
  },
  subtotalRow: {
    backgroundColor: "#EBF4FF",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  btnAgregar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: GREEN,
    borderRadius: 14,
    paddingVertical: 15,
    marginBottom: 4,
    shadowColor: GREEN,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  guiaBox: {
    alignItems: "center",
    paddingVertical: 28,
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: 14,
  },
  tablaHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  colDesc: { flex: 1 },
  colCant: { width: 44, textAlign: "center" },
  colTotal: { width: 90, textAlign: "right" },
  tablaFila: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderStyle: "dashed",
    borderBottomColor: GRAY_BORDER,
  },
  dividerDashed: {
    height: 1,
    borderTopWidth: 1,
    borderStyle: "dashed",
    borderColor: GRAY_BORDER,
    marginVertical: 8,
  },
  totalRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 8,
  },
  botonesRow: { flexDirection: "row", gap: 10 },
  btnOutline: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderWidth: 1.5,
    borderColor: "#0077EE",
    borderRadius: 14,
    paddingVertical: 14,
  },
  btnOutlineText: { fontWeight: "700", fontSize: 17 },
  btnPrimary: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#0077EE",
    borderRadius: 14,
    paddingVertical: 14,
    shadowColor: "#0077EE",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  btnPrimaryText: { color: "#fff", fontWeight: "700", fontSize: 18 },
  btnDisabled: { backgroundColor: "#C4CBD8", shadowOpacity: 0 },
  ticketCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: GRAY_BORDER,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  ticketStripe: { height: 5 },
  ticketBody: { padding: 16 },
  ticketRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
    marginBottom: 10,
  },
  totalBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  totalBadgeText: { fontSize: 14, fontWeight: "600" },
  metodoPagoGrid: { flexDirection: "row", gap: 12, marginBottom: 4 },
  metodoBtn: {
    flex: 1,
    backgroundColor: "#fff",
    borderWidth: 1.5,
    borderColor: GRAY_BORDER,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    gap: 8,
  },
  metodoBtnActive: {
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  metodoBtnCredito: {
    backgroundColor: "#F59E0B",
    borderColor: "#F59E0B",
    shadowColor: "#F59E0B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  metodoIconBox: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  metodoIconBoxActive: { backgroundColor: "rgba(255,255,255,0.2)" },
  metodoIconBoxCredito: { backgroundColor: "rgba(255,255,255,0.2)" },
  metodoBtnLabel: { fontSize: 18, fontWeight: "700", color: INK },
  metodoBtnLabelActive: { color: "#fff" },
  calculadoraCard: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 16,
    marginTop: 14,
    borderWidth: 1,
    borderColor: GRAY_BORDER,
  },
  inputDinero: {
    backgroundColor: GRAY_LIGHT,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 20,
    fontSize: 34,
    fontWeight: "800",
    textAlign: "center",
    color: INK,
    borderWidth: 1,
    borderColor: GRAY_BORDER,
    letterSpacing: -1,
  },
  vueltoBox: {
    backgroundColor: GREEN_LIGHT,
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 130,
    borderWidth: 1,
    borderColor: "#A7F3D0",
    gap: 2,
  },
  CreditoInfo: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#FFFBEB",
    borderRadius: 12,
    padding: 14,
    marginTop: 14,
    borderWidth: 1,
    borderColor: "#FDE68A",
  },
  btnFinalizar: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: GREEN,
    borderRadius: 14,
    paddingVertical: 16,
    shadowColor: GREEN,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
    zIndex: 999,
  },
  bottomSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 36,
  },
  sheetHandle: {
    width: 36,
    height: 4,
    backgroundColor: GRAY_BORDER,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 16,
  },
  opcionesHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  closeGray: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#9CA3AF",
    alignItems: "center",
    justifyContent: "center",
  },
  opcionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderWidth: 1,
    borderColor: "#C8E0FF",
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    backgroundColor: "#fff",
  },
  opcionBtnRojo: { borderColor: "#FECACA" },
  opcionIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  avisoRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: GRAY_LIGHT,
    borderRadius: 10,
    padding: 10,
    marginTop: 4,
  },
  loaderGlobalContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,255,255,0.85)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9999,
  },
  loaderPanel: {
    backgroundColor: "#fff",
    padding: 24,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
  },
  separadorYaAgregado: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginVertical: 10,
  },
  separadorLinea: { flex: 1, height: 1, backgroundColor: "#D8DCE8" },
  separadorTexto: {
    fontSize: 13,
    fontWeight: "600" as const,
    color: GRAY_TEXT,
    letterSpacing: 0.4,
  },
});
